apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: kube-system
spec :
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1 
       maxUnavailable: 25%
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - image: balavpy20/webapp:tagVersion
          imagePullPolicy: Always
          name: webapp
          ports:
          - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /webapp
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 5
            timeoutSeconds: 15
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: kube-system
  labels:
   app: webapp
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 32200
  selector:
    app: webapp
